#include"ScalarConverter.hpp"

/*
	Bits representation needed to understand : 
	- loss of precision between float/double/int
	- int overflow generated by lost of precision of str->float 
		--> str "2147483647.f" -> float 2147483648 -> int -2147483648
*/

void	ScalarConverter::printFloatBits(__attribute__((unused)) const float & f) 
{
	size_t				len = sizeof(f) * 8;
	const unsigned char	*raw = reinterpret_cast<const unsigned char *>(&f);

	std::cout << "float: " << std::fixed << std::left << std::setw(15) << f << ":\t";
	for (int i = static_cast<int>(len) - 1; i >= 0; --i)
	{
		std::cout << (((raw[i / 8]) >> (i % 8)) & 1);
		if (i == static_cast<int>(len) -1 || i == static_cast<int>(len) -1 - 8)
			std::cout << '.';
	}
	std::cout << std::endl;
}

void	ScalarConverter::printDoubleBits(__attribute__((unused)) const double & d)
{
	size_t				len = sizeof(d) * 8;
	const unsigned char	*raw = reinterpret_cast<const unsigned char *>(&d);

	std::cout << "double: " << std::fixed << std::left << std::setw(30) << d << ":\t";
	for (int i = static_cast<int>(len) - 1; i >= 0; --i)
	{
		std::cout << (((raw[i / 8]) >> (i % 8)) & 1);
		if (i == static_cast<int>(len) -1 || i == static_cast<int>(len) -1 - 11)
			std::cout << '.';
	}
	std::cout << std::endl;
}

void	ScalarConverter::printIntBits(__attribute__((unused)) const int & i)
{
	size_t	len = sizeof(i) * 8;

	std::cout << "int: " << std::left << std::setw(13) << i << ":\t";
	for (int j = static_cast<int>(len) - 1; j >= 0; --j)
	{
		std::cout << ((i >> j) & 1);
		if (j == static_cast<int>(len) - 1)
			std::cout << '.';
	}
	std::cout << std::endl;
}

void	ScalarConverter::printCharBits(__attribute__((unused))const char & c)
{
	size_t	len = sizeof(c) * 8;

	std::cout << "char: " << std::left << std::setw(5) << static_cast<int>(c) << ":\t";
	for (int i = static_cast<int>(len) - 1; i >= 0; --i)
	{
		std::cout << ((c >> i) & 1);
		if (i == static_cast<int>(len) - 1)
			std::cout << '.';
	}
	std::cout << std::endl;
}
