#include"ScalarConverter.hpp"

/*
	Bits representation needed to understand : 
	- loss of precision between float/double/int
	- int overflow generated by lost of precision of str->float 
		--> str "2147483647.f" -> float 2147483648 -> int -2147483648
*/

void	ScalarConverter::printFloatBits(__attribute__((unused)) number val) 
{
	size_t	len = sizeof(float);
	std::cout << len << std::endl;
}

void	ScalarConverter::printDoubleBits(__attribute__((unused)) number val)
{
	size_t	len = sizeof(double);
	std::cout << len << std::endl;
}

void	ScalarConverter::printIntBits(__attribute__((unused)) number val)
{
	size_t	len = sizeof(int);
	std::cout << len << std::endl;
}

void	ScalarConverter::printCharBits(__attribute__((unused)) number val)
{
	size_t	len = sizeof(char);
	std::cout << len << std::endl;
}